name: depcheck.yml

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - '4.12'
    - '4.13'
  pull_request:
    branches:
    - main
    - '4.12'
    - '4.13'

jobs:
  ci:
    name: depcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          auth-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          registry-url: pkgs.dev.azure.com/FuseLabs/_packaging/SDK_JS_org/npm/registry

      - name: yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node16.x-yarn-${{ hashFiles('**/yarn.lock') }}

      # - name: auth setup
      #   run: echo "//pkgs.dev.azure.com/FuseLabs/_packaging/SDK_JS_org/npm/registry/:_authToken=${{ secrets.AZURE_DEVOPS_TOKEN }}" >> .npmrc

      - name: yarn
        run: yarn --frozen-lockfile

      - name: yarn depcheck
        run: yarn depcheck
